// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvfppaqyacmxxbqpnqoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZnBwYXF5YWNteHhicXBucW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4ODc5MzIsImV4cCI6MjA4NzQ2MzkzMn0.K8C6E1vg2CoPmw_axizhP4jmU6oMdE-9Z8unpgRl29U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
