// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qslvdorqmfwbbyvufnxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbHZkb3JxbWZ3YmJ5dnVmbnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzI0NjQsImV4cCI6MjA2ODI0ODQ2NH0.yrBVNKgP-7JI9w06AwSigREdQTdFXd-gzRa6WMb_Fs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});